project:
  type: manuscript
  output-dir: ./docs

execute:
  freeze: auto

manuscript:
  article: index.qmd

# Table of contents
toc: true
number-sections: true

# Bibliography
bibliography: biblio.bib
csl: assets/frontiers.csl
highlight-style: github

format:
  html:
    theme: ['sandstone', assets/custom.scss]
    html-math-method: katex
    page-layout: full
    smooth-scroll: true

  pdf:
    documentclass: scrartcl
    papersize: a4
    geometry:
      - margin=1in
    linestretch: 1.25
    fontfamily: roboto
    keep-tex: true
    colorlinks: true

  docx: default
